### ISSUE TITLE
Experimental RoseTree tests  failing

### ISSUE THREAD

**Issue by jackfoxy** [fsprojects/FSharpx.Collections#114]
### Description

2 ptestPropertyWithConfig fail

### Repro steps

change to testPropertyWithConfig and run tests

### Expected behavior

pass
See commit 2918045 for tests passing as NUnit tests before conversion to Expecto and F# was at 4.0. 

Since then projects have been updated first to F#.Core 4.1 and now 4.5.

Also previous passing tests were on older version of FsCheck.

### Actual behavior

Message: The type System.Exception is not handled automatically by FsCheck. Consider using another type or writing and registering a generator for it.

````
Result StackTrace:	
at FsCheck.ReflectArbitrary.reflectObj@124-10.Invoke(String message)
   at FsCheck.ReflectArbitrary.reflectGenObj@129.Invoke(Type t)
   at FsCheck.Common.f@1[a,b](IDictionary`2 memo, FSharpFunc`2 f, a n, Unit _arg1)
   at FsCheck.Common.memoizeWith[a,b](IDictionary`2 memo, FSharpFunc`2 f, a n)
   at FsCheck.Common.memoize@22.Invoke(a n)
   at FsCheck.Arb.Derive@1146.get_Generator()
   at FsCheck.Arbitrary`1.FsCheck-IArbitrary-get_GeneratorObj()
   at FsCheck.ReflectArbitrary.gs@64.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Microsoft.FSharp.Collections.SeqModule.ToArray[T](IEnumerable`1 source)
   at FsCheck.ReflectArbitrary.productGen@63[a](FSharpFunc`2 getGenerator, IEnumerable`1 ts, FSharpFunc`2 create)
   at FsCheck.ReflectArbitrary.productGen@63-2T.Invoke(IEnumerable`1 ts, FSharpFunc`2 create)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at FsCheck.ReflectArbitrary.small@96-1.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at FsCheck.ReflectArbitrary.getgs@99.Invoke(Int32 size)
   at FsCheck.Gen.Sized@147.Invoke(Int32 n, StdGen r)
   at <StartupCode$FsCheck>.$Gen.Map@16.Invoke(Int32 n, StdGen r)
   at <StartupCode$FsCheck>.$Gen.Map@16.Invoke(Int32 n, StdGen r)
   at <StartupCode$FsCheck>.$Gen.Map@16.Invoke(Int32 n, StdGen r)
   at FsCheck.Gen.Sequence@379-2.Invoke(Int32 size, StdGen rnd)
   at <StartupCode$FsCheck>.$Gen.Map@16.Invoke(Int32 n, StdGen r)
   at <StartupCode$FsCheck>.$Gen.Map@16.Invoke(Int32 n, StdGen r)
   at <StartupCode$FsCheck>.$Gen.Map@16.Invoke(Int32 n, StdGen r)
   at <StartupCode$FsCheck>.$Gen.Map@16.Invoke(Int32 n, StdGen r)
   at FsCheck.Gen.Sequence@379-2.Invoke(Int32 size, StdGen rnd)
   at <StartupCode$FsCheck>.$Gen.Map@16.Invoke(Int32 n, StdGen r)
   at <StartupCode$FsCheck>.$Gen.Map@16.Invoke(Int32 n, StdGen r)
   at <StartupCode$FsCheck>.$Gen.Map@16.Invoke(Int32 n, StdGen r)
   at FsCheck.Gen.go@345-3[b](FSharpList`1 gs, FSharpList`1 acc, Int32 size, StdGen r0)
   at FsCheck.Gen.SequenceToList@352.Invoke(Int32 n, StdGen r)
   at <StartupCode$FsCheck>.$Gen.Map@16.Invoke(Int32 n, StdGen r)
   at FsCheck.GenBuilder.Bind@88.Invoke(Int32 n, StdGen r0)
   at FsCheck.GenBuilder.Bind@88.Invoke(Int32 n, StdGen r0)
   at FsCheck.Runner.test@96-1.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
   at FsCheck.Common.loop@53-1.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
   at FsCheck.Common.takeWhilePlusLast@61.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.Fold[T,TState](FSharpFunc`2 folder, TState state, IEnumerable`1 source)
   at FsCheck.Runner.runner[a](Config config, a prop)
   at FsCheck.Runner.check[a](Config config, a p)
   at FsCheck.Check.One[Testable](Config config, Testable property)
   at Expecto.ExpectoFsCheckModule.test@90.Invoke(FsCheckConfig config)
   at Expecto.Impl.execTestAsync@887-1.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2)
   at <StartupCode$FSharp-Core>.$Async.StartChild@1641-5.Invoke(AsyncActivation`1 ctxt)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
````

### Comments
The tests die in FsCheck on the [equality comparison](https://github.com/fsprojects/FSharpx.Collections/blob/68acb6cb5e860ced24a03c95922e6809352b8c4b/src/FSharpx.Collections.Experimental/RoseTree.fs#L25)

Hypotheses:

1) NUnit had weaker equality constraints than Expecto. I have already seen this in many other refactors, but managed to find way to get Expecto to do the comparison.

2) LazyList is not actually equitable or comparable, so it is a bit mysterious to me how RoseTree equality works.

3) Change to FsCheck. It appears to be trapping a throw which is not making debugging any easier

**Comment by teo-tsirpanis** [comment]
Doesn't a simple equality check force evaluating the entire tree? Also, the existence of a `LazyList` means that the tree can be of infinite length!

Shouldn't `RoseForest<'T>` simply be `RoseTree<'T> list`?

**Comment by teo-tsirpanis** [comment]
~~Because we are preparing for a 2.0 release, this breaking change would be tolerable.~~

Never mind, `RoseTree` is experimental.
