### ISSUE TITLE
Enumerating an empty RandomAccessList fails

### ISSUE THREAD

**Issue by xavierzwirtz** [fsprojects/FSharpx.Collections#44]
```f#
for i in RandomAccessList.empty do
    ignore()
```

Fails with
```
System.IndexOutOfRangeException : Index was outside the bounds of the array.
   at FSharpx.Collections.RandomAccessList`1.ArrayFor(Int32 i) in D:\code\FSharpx.Collections\src\FSharpx.Collections\RandomAccessList.fs:line 199
   at FSharpx.Collections.RandomAccessList`1.rangedIterator[T](Int32 startIndex, Int32 endIndex) in D:\code\FSharpx.Collections\src\FSharpx.Collections\RandomAccessList.fs:line 227
   at FSharpx.Collections.RandomAccessList`1.System-Collections-Generic-IEnumerable`1-GetEnumerator() in D:\code\FSharpx.Collections\src\FSharpx.Collections\RandomAccessList.fs:line 327
```

**Comment by mausch** [comment]
pinging @jackfoxy

**Comment by jackfoxy** [comment]
I'll try to take a look at it this weekend. @xavierzwirtz @mausch

**Comment by jackfoxy** [comment]
pending https://github.com/fsprojects/FSharpx.Collections/pull/45

**Comment by xavierzwirtz** [comment]
Confirming that `1.12.4` fixed my issue. Thanks for the help @jackfoxy.

**Comment by jackfoxy** [comment]
@xavierzwirtz glad to know you are using RandomAccessList.
